name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT_JAV_PLANT }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/your-org-or-username/your-repo-name:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-push  # Ensure deployment only happens after the build-push job succeeds

  #   steps:
  #     # Deploy to Railway
  #     - name: Trigger Railway Deployment
  #       uses: railwayapp/cli-action@v1
  #       with:
  #         command: up
  #       env:
  #         RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
